version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3.2.0
  codecov: codecov/codecov@3.3.0
jobs:
    # 👇 Adds Chromatic as a job
  chromatic-deployment:
    docker:
      - image: cimg/node:21.1.0
    working_directory: ~/stein-saks-papir
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
  build:
    working_directory: ~/stein-saks-papir
    docker:
      - image: cimg/node:21.1.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v2-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Jest Tests
          command: npm test
      - codecov/upload
    parallelism: 6
workflows:
  # 👇 Adds Chromatic to the workflow
  chromatic-deploy:
    jobs:
      - build:
          name: Build React project
      - cypress/run:
          name: Run Cypress E2E tests with Electron
          cypress-command: npx cypress run --browser electron
          start-command: npm run dev
          # executor: with-chrome-and-firefox